/* generated by hagane — do not edit */
#include "hagane_rt.h"
#include "hagane_map.h"

bool hg_example_com_strings_test_init_guard;
void hg_example_com_strings_test_init(void);
void hg_example_com_strings_test_main(void);
typedef struct { hg_iface_t elems[1]; } hg_array_hg_iface_t_1_t;

void hg_example_com_strings_test_init(void) {
    goto blk0;
blk0:;
    hg_nil_check(&hg_example_com_strings_test_init_guard, "?", 0);
    bool t0 = *((bool*)&hg_example_com_strings_test_init_guard);
    if (t0) goto blk2; else goto blk1;
blk1:;
    hg_nil_check(&hg_example_com_strings_test_init_guard, "?", 0);
    *(&hg_example_com_strings_test_init_guard) = true;
    /* call to fmt.init skipped */
    goto blk2;
blk2:;
    return;
}

void hg_example_com_strings_test_main(void) {
    goto blk0;
blk0:;
    hg_string_t t0 = hg_string_concat(hg_string_lit("hello"), hg_string_lit(", "));
    hg_string_t t1 = hg_string_concat(t0, hg_string_lit("world"));
    hg_string_t t2 = hg_string_concat(t1, hg_string_lit("!"));
    hg_array_hg_iface_t_1_t* t3 = (hg_array_hg_iface_t_1_t*)hg_alloc(sizeof(hg_array_hg_iface_t_1_t));
    hg_bounds_check(((int64_t)0), 1, "?", 0);
    hg_iface_t* t4 = &(*t3).elems[((int64_t)0)];
    hg_iface_t t5; { hg_string_t *_box = (hg_string_t*)hg_alloc(sizeof(hg_string_t)); *_box = t2; t5.data = _box; t5.itab = (const void*)&hg_itab_string; }
    *(t4) = t5;
    hg_slice_hg_iface_t_t t6 = {.ptr = (*t3).elems+(0), .len = (1)-(0), .cap = 1-(0)};
    hg_fmt_println(t6);
    int64_t t8 = t2.len;
    hg_array_hg_iface_t_1_t* t9 = (hg_array_hg_iface_t_1_t*)hg_alloc(sizeof(hg_array_hg_iface_t_1_t));
    hg_bounds_check(((int64_t)0), 1, "?", 0);
    hg_iface_t* t10 = &(*t9).elems[((int64_t)0)];
    hg_iface_t t11; { int64_t *_box = (int64_t*)hg_alloc(sizeof(int64_t)); *_box = t8; t11.data = _box; t11.itab = (const void*)&hg_itab_int64; }
    *(t10) = t11;
    hg_slice_hg_iface_t_t t12 = {.ptr = (*t9).elems+(0), .len = (1)-(0), .cap = 1-(0)};
    hg_fmt_println(t12);
    bool t14 = hg_string_equal(hg_string_lit("hello"), hg_string_lit("hello"));
    hg_array_hg_iface_t_1_t* t15 = (hg_array_hg_iface_t_1_t*)hg_alloc(sizeof(hg_array_hg_iface_t_1_t));
    hg_bounds_check(((int64_t)0), 1, "?", 0);
    hg_iface_t* t16 = &(*t15).elems[((int64_t)0)];
    hg_iface_t t17; { bool *_box = (bool*)hg_alloc(sizeof(bool)); *_box = t14; t17.data = _box; t17.itab = (const void*)&hg_itab_bool; }
    *(t16) = t17;
    hg_slice_hg_iface_t_t t18 = {.ptr = (*t15).elems+(0), .len = (1)-(0), .cap = 1-(0)};
    hg_fmt_println(t18);
    bool t20 = hg_string_compare(hg_string_lit("hello"), hg_string_lit("world")) < 0;
    hg_array_hg_iface_t_1_t* t21 = (hg_array_hg_iface_t_1_t*)hg_alloc(sizeof(hg_array_hg_iface_t_1_t));
    hg_bounds_check(((int64_t)0), 1, "?", 0);
    hg_iface_t* t22 = &(*t21).elems[((int64_t)0)];
    hg_iface_t t23; { bool *_box = (bool*)hg_alloc(sizeof(bool)); *_box = t20; t23.data = _box; t23.itab = (const void*)&hg_itab_bool; }
    *(t22) = t23;
    hg_slice_hg_iface_t_t t24 = {.ptr = (*t21).elems+(0), .len = (1)-(0), .cap = 1-(0)};
    hg_fmt_println(t24);
    return;
}


int main(int argc, char **argv) {
    hg_runtime_init();
    hg_example_com_strings_test_main();
    return 0;
}
