// Package emit translates go/ssa into C11 source files.
package emit

import (
	"bytes"
	"fmt"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/ssa"
	"golang.org/x/tools/go/ssa/ssautil"

	"github.com/tamnd/hagane/frontend"
)

// Emitter holds state for emitting one Go package as C.
type Emitter struct {
	prog       *frontend.Program
	pkg        *ssa.Package
	fset       *token.FileSet
	buf        *bytes.Buffer
	hdrbuf     *bytes.Buffer // header (forward decls)
	sliceTypes map[string]bool
	mapTypes   map[string]bool
	nextTypes  map[string]bool      // Next result tuple typedefs already emitted
	mapFuncs   map[string]bool      // hash/eq helper function names already emitted
	ifacePairs map[string]ifacePair // (concrete, iface) pairs for M3 itab emission
	transpiled map[string]bool      // paths of packages being emitted as C
}

// rtSliceTypes lists slice typedefs already defined in hagane_rt.h so we don't re-emit them.
var rtSliceTypes = map[string]bool{
	"hg_slice_bool_t":        true,
	"hg_slice_int8_t":        true,
	"hg_slice_int16_t":       true,
	"hg_slice_int32_t":       true,
	"hg_slice_int64_t":       true,
	"hg_slice_uint8_t":       true,
	"hg_slice_uint16_t":      true,
	"hg_slice_uint32_t":      true,
	"hg_slice_uint64_t":      true,
	"hg_slice_uintptr_t":     true,
	"hg_slice_float_t":       true,
	"hg_slice_double_t":      true,
	"hg_slice_hg_string_t_t": true,
	"hg_slice_hg_iface_t_t":  true,
	"hg_slice_voidptr_t":     true,
}

// New creates an Emitter for the given loaded program.
func New(prog *frontend.Program) *Emitter {
	// pre-seed with types already in the runtime header
	st := make(map[string]bool)
	for k, v := range rtSliceTypes {
		st[k] = v
	}
	return &Emitter{
		prog:       prog,
		fset:       prog.Fset,
		sliceTypes: st,
		mapTypes:   make(map[string]bool),
		nextTypes:  make(map[string]bool),
		mapFuncs:   make(map[string]bool),
		ifacePairs: make(map[string]ifacePair),
		transpiled: make(map[string]bool),
	}
}

// EmitAll emits all packages to .h + .c files in outDir.
// It also copies the runtime header and implementation.
func (e *Emitter) EmitAll(outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	// write runtime files
	if err := writeRuntimeFiles(outDir); err != nil {
		return err
	}

	// Collect the set of packages we will transpile so each package's C file
	// can include the headers of its dependencies.
	e.transpiled = make(map[string]bool)
	for _, pkg := range e.prog.AllPkgs {
		if !skipPkg(pkg) {
			e.transpiled[pkg.Pkg.Path()] = true
		}
	}

	// AllPkgs is in post-order (leaves first), so dependencies are emitted
	// before the packages that import them.
	for _, pkg := range e.prog.AllPkgs {
		if skipPkg(pkg) {
			continue
		}
		hdr, body, err := e.emitPkgSplit(pkg)
		if err != nil {
			return fmt.Errorf("emit %s: %w", pkg.Pkg.Path(), err)
		}
		base := pkgToFileName(pkg.Pkg.Path())
		if err := os.WriteFile(filepath.Join(outDir, base+".h"), hdr, 0644); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(outDir, base+".c"), body, 0644); err != nil {
			return err
		}
	}
	return nil
}

// emitPkgSplit runs the emitter for pkg and returns (header, body) bytes.
// The header contains typedefs and prototypes (include-guarded).
// The body contains function definitions; it includes the package's own header.
func (e *Emitter) emitPkgSplit(pkg *ssa.Package) (hdr []byte, body []byte, err error) {
	if err = e.runEmitPkg(pkg); err != nil {
		return nil, nil, err
	}

	base := pkgToFileName(pkg.Pkg.Path())
	guard := strings.ToUpper(base) + "_H"

	// Build header: include guard + runtime headers + dep headers + own decls.
	var hb bytes.Buffer
	fmt.Fprintf(&hb, "/* generated by hagane — do not edit */\n")
	fmt.Fprintf(&hb, "#ifndef %s\n#define %s\n\n", guard, guard)
	hb.WriteString("#include \"hagane_rt.h\"\n")
	hb.WriteString("#include \"hagane_map.h\"\n")
	for _, imp := range transpiledImports(e, pkg) {
		fmt.Fprintf(&hb, "#include \"%s.h\"\n", pkgToFileName(imp))
	}
	hb.WriteString("\n")
	hb.Write(e.hdrbuf.Bytes())
	fmt.Fprintf(&hb, "\n#endif /* %s */\n", guard)

	// Build body: include own header then function bodies.
	var bb bytes.Buffer
	bb.WriteString("/* generated by hagane — do not edit */\n")
	fmt.Fprintf(&bb, "#include \"%s.h\"\n\n", base)
	bb.Write(e.buf.Bytes())
	if pkg.Pkg.Name() == "main" {
		prefix := pkgCPrefix(pkg.Pkg.Path())
		bb.WriteString("\nint main(int argc, char **argv) {\n")
		bb.WriteString("    hg_runtime_init();\n")
		fmt.Fprintf(&bb, "    %smain();\n", prefix)
		bb.WriteString("    return 0;\n")
		bb.WriteString("}\n")
	}

	return hb.Bytes(), bb.Bytes(), nil
}

// EmitPkg emits a single package to a writer (for testing / inspection).
func (e *Emitter) EmitPkg(pkg *ssa.Package, w io.Writer) error {
	if err := e.runEmitPkg(pkg); err != nil {
		return err
	}
	// Assemble old-style single-file output for test inspection.
	var out bytes.Buffer
	out.WriteString("/* generated by hagane — do not edit */\n")
	out.WriteString("#include \"hagane_rt.h\"\n")
	out.WriteString("#include \"hagane_map.h\"\n\n")
	out.Write(e.hdrbuf.Bytes())
	out.WriteString("\n")
	out.Write(e.buf.Bytes())
	_, err := w.Write(out.Bytes())
	return err
}

// runEmitPkg populates e.hdrbuf (typedefs + prototypes) and e.buf (function bodies) for pkg.
func (e *Emitter) runEmitPkg(pkg *ssa.Package) error {
	e.pkg = pkg
	e.buf = &bytes.Buffer{}
	e.hdrbuf = &bytes.Buffer{}
	// reset but keep runtime header types pre-seeded
	st := make(map[string]bool)
	for k, v := range rtSliceTypes {
		st[k] = v
	}
	e.sliceTypes = st
	e.mapTypes = make(map[string]bool)
	e.nextTypes = make(map[string]bool)
	e.mapFuncs = make(map[string]bool)
	e.ifacePairs = make(map[string]ifacePair)

	// collect all functions in this package (including methods) via AllFunctions
	var fns []*ssa.Function
	for fn := range ssautil.AllFunctions(e.prog.SSA) {
		if fn.Package() == pkg && fn.Blocks != nil {
			fns = append(fns, fn)
		}
	}
	sort.Slice(fns, func(i, j int) bool {
		return fns[i].Name() < fns[j].Name()
	})

	// expand to include anonymous functions (closures)
	var allFns []*ssa.Function
	var collectAnon func(fn *ssa.Function)
	anonSeen := map[*ssa.Function]bool{}
	collectAnon = func(fn *ssa.Function) {
		if anonSeen[fn] {
			return
		}
		anonSeen[fn] = true
		allFns = append(allFns, fn)
		for _, anon := range fn.AnonFuncs {
			collectAnon(anon)
		}
	}
	for _, fn := range fns {
		collectAnon(fn)
	}

	// emit forward declarations into hdrbuf
	pe := &pkgEmitter{e: e, pkg: pkg}
	pe.emitHeader()

	// emit prototypes for anonymous functions (not in pkg.Members)
	for _, fn := range allFns {
		if fn.Blocks == nil {
			continue
		}
		if _, inMembers := pkg.Members[fn.Name()]; inMembers {
			continue // top-level already emitted by emitHeader
		}
		// anon func prototype
		if len(fn.FreeVars) > 0 {
			// env struct must be emitted before the prototype
			pe.emitClosureEnv(fn)
		}
		if fn.Signature.Results().Len() > 1 {
			decl := retStructDecl(e, pe.prefix(), methodCBaseName(fn), fn.Signature.Results())
			fmt.Fprintf(e.hdrbuf, "%s\n", decl)
		}
		fmt.Fprintf(e.hdrbuf, "%s;\n", pe.funcSignature(fn))
	}

	// emit function bodies
	for _, fn := range allFns {
		if fn.Blocks == nil {
			continue // external / declared only
		}
		pe.emitFunc(fn)
	}

	// emit GoType globals and itab globals for M3 interface dispatch
	e.emitIfaceDecls()

	return nil
}

// transpiledImports returns the import paths of pkg's direct imports that are
// being transpiled (i.e., in e.transpiled), sorted for deterministic output.
func transpiledImports(e *Emitter, pkg *ssa.Package) []string {
	var paths []string
	for _, imp := range pkg.Pkg.Imports() {
		if e.transpiled[imp.Path()] {
			paths = append(paths, imp.Path())
		}
	}
	sort.Strings(paths)
	return paths
}

// transpilableStdlib is the set of standard library packages we know how to
// emit as C. Everything else in the stdlib is provided by the hagane runtime.
var transpilableStdlib = map[string]bool{
	"container/heap": true,
	"container/list": true,
	"container/ring": true,
}

func skipPkg(pkg *ssa.Package) bool {
	path := pkg.Pkg.Path()
	// User packages (module paths contain a dot in the first segment) are
	// always emitted.
	first := path
	if i := strings.IndexByte(path, '/'); i >= 0 {
		first = path[:i]
	}
	if strings.ContainsRune(first, '.') {
		return false
	}
	// For stdlib, only emit packages in the explicit allowlist.
	return !transpilableStdlib[path]
}

func pkgToFileName(path string) string {
	return strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(path)
}

func pkgCPrefix(path string) string {
	if path == "main" {
		return "hg_main_"
	}
	mangled := strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(path)
	return "hg_" + mangled + "_"
}
