// Package emit translates go/ssa into C11 source files.
package emit

import (
	"bytes"
	"fmt"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/ssa"
	"golang.org/x/tools/go/ssa/ssautil"

	"github.com/tamnd/hagane/frontend"
)

// Emitter holds state for emitting one Go package as C.
type Emitter struct {
	prog       *frontend.Program
	pkg        *ssa.Package
	fset       *token.FileSet
	buf        *bytes.Buffer
	hdrbuf     *bytes.Buffer // header (forward decls)
	sliceTypes map[string]bool
	mapTypes   map[string]bool
	nextTypes  map[string]bool // Next result tuple typedefs already emitted
	mapFuncs   map[string]bool // hash/eq helper function names already emitted
	ifacePairs map[string]ifacePair // (concrete, iface) pairs for M3 itab emission
}

// rtSliceTypes lists slice typedefs already defined in hagane_rt.h so we don't re-emit them.
var rtSliceTypes = map[string]bool{
	"hg_slice_bool_t":        true,
	"hg_slice_int8_t":        true,
	"hg_slice_int16_t":       true,
	"hg_slice_int32_t":       true,
	"hg_slice_int64_t":       true,
	"hg_slice_uint8_t":       true,
	"hg_slice_uint16_t":      true,
	"hg_slice_uint32_t":      true,
	"hg_slice_uint64_t":      true,
	"hg_slice_uintptr_t":     true,
	"hg_slice_float_t":       true,
	"hg_slice_double_t":      true,
	"hg_slice_hg_string_t_t": true,
	"hg_slice_hg_iface_t_t":  true,
	"hg_slice_voidptr_t":     true,
}

// New creates an Emitter for the given loaded program.
func New(prog *frontend.Program) *Emitter {
	// pre-seed with types already in the runtime header
	st := make(map[string]bool)
	for k, v := range rtSliceTypes {
		st[k] = v
	}
	return &Emitter{
		prog:       prog,
		fset:       prog.Fset,
		sliceTypes: st,
		mapTypes:   make(map[string]bool),
		nextTypes:  make(map[string]bool),
		mapFuncs:   make(map[string]bool),
		ifacePairs: make(map[string]ifacePair),
	}
}

// EmitAll emits all packages to .c files in outDir.
// It also copies the runtime header and implementation.
func (e *Emitter) EmitAll(outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	// write runtime files
	if err := writeRuntimeFiles(outDir); err != nil {
		return err
	}

	for _, pkg := range e.prog.AllPkgs {
		if skipPkg(pkg) {
			continue
		}
		c, err := e.emitPkg(pkg)
		if err != nil {
			return fmt.Errorf("emit %s: %w", pkg.Pkg.Path(), err)
		}
		name := pkgToFileName(pkg.Pkg.Path()) + ".c"
		if err := os.WriteFile(filepath.Join(outDir, name), c, 0644); err != nil {
			return err
		}
	}
	return nil
}

// EmitPkg emits a single package to a writer (for testing / inspection).
func (e *Emitter) EmitPkg(pkg *ssa.Package, w io.Writer) error {
	c, err := e.emitPkg(pkg)
	if err != nil {
		return err
	}
	_, err = w.Write(c)
	return err
}

func (e *Emitter) emitPkg(pkg *ssa.Package) ([]byte, error) {
	e.pkg = pkg
	e.buf = &bytes.Buffer{}
	e.hdrbuf = &bytes.Buffer{}
	// reset but keep runtime header types pre-seeded
	st := make(map[string]bool)
	for k, v := range rtSliceTypes {
		st[k] = v
	}
	e.sliceTypes = st
	e.mapTypes   = make(map[string]bool)
	e.nextTypes  = make(map[string]bool)
	e.mapFuncs   = make(map[string]bool)
	e.ifacePairs = make(map[string]ifacePair)

	// collect all functions in this package (including methods) via AllFunctions
	var fns []*ssa.Function
	for fn := range ssautil.AllFunctions(e.prog.SSA) {
		if fn.Package() == pkg && fn.Blocks != nil {
			fns = append(fns, fn)
		}
	}
	sort.Slice(fns, func(i, j int) bool {
		return fns[i].Name() < fns[j].Name()
	})

	// expand to include anonymous functions (closures)
	var allFns []*ssa.Function
	var collectAnon func(fn *ssa.Function)
	anonSeen := map[*ssa.Function]bool{}
	collectAnon = func(fn *ssa.Function) {
		if anonSeen[fn] {
			return
		}
		anonSeen[fn] = true
		allFns = append(allFns, fn)
		for _, anon := range fn.AnonFuncs {
			collectAnon(anon)
		}
	}
	for _, fn := range fns {
		collectAnon(fn)
	}

	// emit forward declarations into hdrbuf
	pe := &pkgEmitter{e: e, pkg: pkg}
	pe.emitHeader()

	// emit prototypes for anonymous functions (not in pkg.Members)
	for _, fn := range allFns {
		if fn.Blocks == nil {
			continue
		}
		if _, inMembers := pkg.Members[fn.Name()]; inMembers {
			continue // top-level already emitted by emitHeader
		}
		// anon func prototype
		if len(fn.FreeVars) > 0 {
			// env struct must be emitted before the prototype
			pe.emitClosureEnv(fn)
		}
		if fn.Signature.Results().Len() > 1 {
			decl := retStructDecl(e, pe.prefix(), methodCBaseName(fn), fn.Signature.Results())
			fmt.Fprintf(e.hdrbuf, "%s\n", decl)
		}
		fmt.Fprintf(e.hdrbuf, "%s;\n", pe.funcSignature(fn))
	}

	// emit function bodies
	for _, fn := range allFns {
		if fn.Blocks == nil {
			continue // external / declared only
		}
		pe.emitFunc(fn)
	}

	// emit GoType globals and itab globals for M3 interface dispatch
	e.emitIfaceDecls()

	// assemble: preamble + header + body
	var out bytes.Buffer
	out.WriteString("/* generated by hagane — do not edit */\n")
	out.WriteString("#include \"hagane_rt.h\"\n")
	out.WriteString("#include \"hagane_map.h\"\n\n")
	out.Write(e.hdrbuf.Bytes())
	out.WriteString("\n")
	out.Write(e.buf.Bytes())

	// if this is the main package, add C main()
	if pkg.Pkg.Name() == "main" {
		prefix := pkgCPrefix(pkg.Pkg.Path())
		out.WriteString("\nint main(int argc, char **argv) {\n")
		out.WriteString("    hg_runtime_init();\n")
		fmt.Fprintf(&out, "    %smain();\n", prefix)
		out.WriteString("    return 0;\n")
		out.WriteString("}\n")
	}

	return out.Bytes(), nil
}

func skipPkg(pkg *ssa.Package) bool {
	path := pkg.Pkg.Path()
	// skip stdlib packages we can't/don't transpile in M0
	skip := []string{"fmt", "io", "os", "runtime", "reflect",
		"sync", "sync/atomic", "math", "strconv", "unicode",
		"unicode/utf8", "bytes", "strings", "sort"}
	for _, s := range skip {
		if path == s || strings.HasPrefix(path, s+"/") {
			return true
		}
	}
	return false
}

func pkgToFileName(path string) string {
	return strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(path)
}

func pkgCPrefix(path string) string {
	if path == "main" {
		return "hg_main_"
	}
	mangled := strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(path)
	return "hg_" + mangled + "_"
}
