package emit

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/ssa"
)

// TestEntry describes a single Test* function to run.
type TestEntry struct {
	CName   string // C function name, e.g. hg_main_TestFoo
	GoName  string // Go name, e.g. TestFoo
	PkgPath string
}

// EmitAllTest emits all packages (with test packages) to outDir and writes
// a test runner main.c that calls every Test* function.
func (e *Emitter) EmitAllTest(outDir string) ([]TestEntry, error) {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return nil, err
	}
	if err := writeRuntimeFiles(outDir); err != nil {
		return nil, err
	}

	// Mark which packages we will transpile.
	e.transpiled = make(map[string]bool)
	for _, pkg := range e.prog.AllPkgs {
		if !skipPkgTest(pkg) {
			e.transpiled[pkg.Pkg.Path()] = true
		}
	}

	var tests []TestEntry
	var pkgHeaders []string // base file names of emitted packages (for the runner)
	var pkgInits []string   // C names of init functions, in emission order

	for _, pkg := range e.prog.AllPkgs {
		if skipPkgTest(pkg) {
			continue
		}
		hdr, body, err := e.emitPkgSplitTest(pkg)
		if err != nil {
			return nil, fmt.Errorf("emit %s: %w", pkg.Pkg.Path(), err)
		}
		base := pkgToFileName(pkg.Pkg.Path())
		if err := os.WriteFile(filepath.Join(outDir, base+".h"), hdr, 0644); err != nil {
			return nil, err
		}
		if err := os.WriteFile(filepath.Join(outDir, base+".c"), body, 0644); err != nil {
			return nil, err
		}
		pkgHeaders = append(pkgHeaders, base)

		// track init function for this package (SSA always synthesizes one)
		prefix := pkgCPrefix(pkg.Pkg.Path())
		if mem, ok := pkg.Members["init"]; ok {
			if fn, ok := mem.(*ssa.Function); ok && fn.Blocks != nil {
				pkgInits = append(pkgInits, prefix+"init")
			}
		}

		// collect Test* functions
		for _, name := range sortedMemberNames(pkg) {
			if !strings.HasPrefix(name, "Test") {
				continue
			}
			mem, ok := pkg.Members[name]
			if !ok {
				continue
			}
			fn, ok := mem.(*ssa.Function)
			if !ok || fn.Blocks == nil {
				continue
			}
			// must be func(*testing.T)
			sig := fn.Signature
			if sig.Params().Len() != 1 {
				continue
			}
			tests = append(tests, TestEntry{
				CName:   prefix + name,
				GoName:  name,
				PkgPath: pkg.Pkg.Path(),
			})
		}
	}

	// Write the test runner main C file.
	runner, err := buildTestRunnerC(pkgHeaders, pkgInits, tests)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(filepath.Join(outDir, "hg_testmain.c"), runner, 0644); err != nil {
		return nil, err
	}

	return tests, nil
}

// emitPkgSplitTest is like emitPkgSplit but never emits a C main() function.
func (e *Emitter) emitPkgSplitTest(pkg *ssa.Package) (hdr []byte, body []byte, err error) {
	isTestPkg := strings.HasSuffix(pkg.Pkg.Name(), "_test")
	// Emit all functions including methods of test-package types.
	// runEmitTestOnlyFns used to skip non-Test* bodies, but that left itab slots
	// (for types like adversaryTestingData, intPairs, myStructs) without definitions.
	if err = e.runEmitPkg(pkg); err != nil {
		return nil, nil, err
	}

	base := pkgToFileName(pkg.Pkg.Path())
	guard := strings.ToUpper(base) + "_H"

	var hb bytes.Buffer
	fmt.Fprintf(&hb, "/* generated by hagane — do not edit */\n")
	fmt.Fprintf(&hb, "#ifndef %s\n#define %s\n\n", guard, guard)
	hb.WriteString("#include \"hagane_rt.h\"\n")
	hb.WriteString("#include \"hagane_map.h\"\n")
	if !isTestPkg {
		for _, imp := range transpiledImports(e, pkg) {
			fmt.Fprintf(&hb, "#include \"%s.h\"\n", pkgToFileName(imp))
		}
	} else {
		// test pkg: only include transpiled non-test deps
		for _, imp := range pkg.Pkg.Imports() {
			if e.transpiled[imp.Path()] && !strings.HasSuffix(imp.Name(), "_test") {
				fmt.Fprintf(&hb, "#include \"%s.h\"\n", pkgToFileName(imp.Path()))
			}
		}
	}
	hb.WriteString("\n")
	hb.Write(e.hdrbuf.Bytes())
	fmt.Fprintf(&hb, "\n#endif /* %s */\n", guard)

	var bb bytes.Buffer
	bb.WriteString("/* generated by hagane — do not edit */\n")
	fmt.Fprintf(&bb, "#include \"%s.h\"\n\n", base)
	bb.Write(e.buf.Bytes())

	return hb.Bytes(), bb.Bytes(), nil
}

// runEmitTestOnlyFns emits only Test* functions from a _test package,
// skipping all testing infrastructure globals and init functions.
//
// Strategy: run the full runEmitPkg to get complete type declarations and method
// prototypes into hdrbuf, then discard all non-Test* function bodies and re-emit
// only the Test* ones. This avoids duplicating the type/prototype logic.
func (e *Emitter) runEmitTestOnlyFns(pkg *ssa.Package) error {
	// Run the full package emitter to populate hdrbuf and set up all types,
	// struct typedefs, method prototypes, and itab globals.
	if err := e.runEmitPkg(pkg); err != nil {
		return err
	}

	// Discard all function bodies from the full emit — we only want Test* ones.
	// Do NOT reset ifacePairs: runEmitPkg already emitted all itab globals into hdrbuf
	// (including those used by Test* functions). Resetting and re-emitting would cause
	// duplicate-definition errors.
	e.buf = &bytes.Buffer{}

	pe := &pkgEmitter{e: e, pkg: pkg}

	// Collect Test* functions (package-level members).
	var testFns []*ssa.Function
	for name, mem := range pkg.Members {
		if !strings.HasPrefix(name, "Test") {
			continue
		}
		fn, ok := mem.(*ssa.Function)
		if !ok || fn.Blocks == nil {
			continue
		}
		testFns = append(testFns, fn)
	}
	sort.Slice(testFns, func(i, j int) bool {
		return testFns[i].Name() < testFns[j].Name()
	})

	// Emit Test* function bodies (and their closures).
	for _, fn := range testFns {
		var allFns []*ssa.Function
		seen := map[*ssa.Function]bool{}
		var collect func(f *ssa.Function)
		collect = func(f *ssa.Function) {
			if seen[f] {
				return
			}
			seen[f] = true
			allFns = append(allFns, f)
			for _, anon := range f.AnonFuncs {
				collect(anon)
			}
		}
		collect(fn)
		for _, f := range allFns {
			if f.Blocks == nil {
				continue
			}
			pe.emitFunc(f)
		}
	}

	return nil
}

// buildTestRunnerC writes the C test harness main that calls every Test* func.
func buildTestRunnerC(pkgHeaders []string, pkgInits []string, tests []TestEntry) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("/* generated by hagane — do not edit */\n")
	b.WriteString("#include \"hagane_rt.h\"\n")
	b.WriteString("#include \"hagane_map.h\"\n")
	for _, h := range pkgHeaders {
		fmt.Fprintf(&b, "#include \"%s.h\"\n", h)
	}
	b.WriteString("\n")

	// forward-declare init functions so main() can call them
	for _, initFn := range pkgInits {
		fmt.Fprintf(&b, "void %s(void);\n", initFn)
	}
	// forward-declare every Test* function (they're already in the pkg headers,
	// but repeat here for readability)
	for _, t := range tests {
		fmt.Fprintf(&b, "void %s(hg_testing_T *t);\n", t.CName)
	}
	b.WriteString("\n")

	b.WriteString("static int hg_run_tests(void) {\n")
	b.WriteString("    int failed = 0;\n")
	b.WriteString("    int total  = 0;\n\n")

	for _, t := range tests {
		goName := t.PkgPath + "." + t.GoName
		fmt.Fprintf(&b, "    /* --- %s --- */\n", goName)
		fmt.Fprintf(&b, "    {\n")
		fmt.Fprintf(&b, "        total++;\n")
		fmt.Fprintf(&b, "        hg_testing_T t = {0};\n")
		// name as hg_string_t literal
		escaped := escapeCStrBytes([]byte(t.GoName))
		fmt.Fprintf(&b, "        t.name = (hg_string_t){.ptr = \"%s\", .len = %d};\n", escaped, len(t.GoName))
		fmt.Fprintf(&b, "        t.has_failnow = 1;\n")
		fmt.Fprintf(&b, "        int jv = setjmp(t.failnow_jmp);\n")
		fmt.Fprintf(&b, "        if (jv == 0) %s(&t);\n", t.CName)
		fmt.Fprintf(&b, "        if (t.skipped) {\n")
		fmt.Fprintf(&b, "            printf(\"--- SKIP: %s\\n\");\n", t.GoName)
		fmt.Fprintf(&b, "        } else if (t.failed) {\n")
		fmt.Fprintf(&b, "            failed++;\n")
		fmt.Fprintf(&b, "            printf(\"--- FAIL: %s\\n\");\n", t.GoName)
		fmt.Fprintf(&b, "        } else {\n")
		fmt.Fprintf(&b, "            printf(\"--- PASS: %s\\n\");\n", t.GoName)
		fmt.Fprintf(&b, "        }\n")
		fmt.Fprintf(&b, "    }\n\n")
	}

	b.WriteString("    printf(\"\\n\");\n")
	b.WriteString("    if (failed > 0) {\n")
	b.WriteString("        printf(\"FAIL\\n\");\n")
	b.WriteString("        printf(\"%d/%d tests failed\\n\", failed, total);\n")
	b.WriteString("    } else {\n")
	b.WriteString("        printf(\"ok\\n\");\n")
	b.WriteString("        printf(\"%d/%d tests passed\\n\", total, total);\n")
	b.WriteString("    }\n")
	b.WriteString("    return failed > 0 ? 1 : 0;\n")
	b.WriteString("}\n\n")

	b.WriteString("int main(int argc, char **argv) {\n")
	b.WriteString("    (void)argc; (void)argv;\n")
	b.WriteString("    hg_runtime_init();\n")
	for _, initFn := range pkgInits {
		fmt.Fprintf(&b, "    %s();\n", initFn)
	}
	b.WriteString("    return hg_run_tests();\n")
	b.WriteString("}\n")

	return b.Bytes(), nil
}

// skipPkgTest is like skipPkg but also allows test packages (name ending in _test)
// and the packages listed in transpilableStdlib. It always skips the synthetic
// test-binary main (path ends with ".test") which we never want to emit.
func skipPkgTest(pkg *ssa.Package) bool {
	path := pkg.Pkg.Path()
	// The Go toolchain creates a synthetic "test binary" package with a path like
	// "example.com/mypkg.test" (package name "main"). Skip it — we generate our
	// own test runner; emitting this causes filename collisions and pulls in all
	// the testing/internal infrastructure.
	if strings.HasSuffix(path, ".test") {
		return true
	}
	// external test packages have names ending in _test — emit them.
	if strings.HasSuffix(pkg.Pkg.Name(), "_test") {
		return false
	}
	return skipPkg(pkg)
}

func sortedMemberNames(pkg *ssa.Package) []string {
	names := make([]string, 0, len(pkg.Members))
	for n := range pkg.Members {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func escapeCStrBytes(b []byte) string {
	var sb strings.Builder
	for _, c := range b {
		switch c {
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '\n':
			sb.WriteString(`\n`)
		case '\t':
			sb.WriteString(`\t`)
		case '\r':
			sb.WriteString(`\r`)
		default:
			sb.WriteByte(c)
		}
	}
	return sb.String()
}
