/* generated by hagane — do not edit */
#include "hagane_rt.h"
#include "hagane_map.h"

bool hg_example_com_primes_init_guard;
void hg_example_com_primes_init(void);
void hg_example_com_primes_main(void);
typedef struct { bool elems[10001]; } hg_array_bool_10001_t;
typedef struct { hg_iface_t elems[1]; } hg_array_hg_iface_t_1_t;

void hg_example_com_primes_init(void) {
    goto blk0;
blk0:;
    hg_nil_check(&hg_example_com_primes_init_guard, "?", 0);
    bool t0 = *((bool*)&hg_example_com_primes_init_guard);
    if (t0) goto blk2; else goto blk1;
blk1:;
    hg_nil_check(&hg_example_com_primes_init_guard, "?", 0);
    *(&hg_example_com_primes_init_guard) = true;
    /* call to fmt.init skipped */
    goto blk2;
blk2:;
    return;
}

void hg_example_com_primes_main(void) {
    int64_t t4;
    memset(&t4, 0, sizeof(t4));
    int64_t t8;
    memset(&t8, 0, sizeof(t8));
    int64_t t15;
    memset(&t15, 0, sizeof(t15));
    int64_t t24;
    memset(&t24, 0, sizeof(t24));
    int64_t t25;
    memset(&t25, 0, sizeof(t25));
    int64_t t28;
    memset(&t28, 0, sizeof(t28));
    goto blk0;
blk0:;
    hg_array_bool_10001_t* t0 = (hg_array_bool_10001_t*)hg_alloc(sizeof(hg_array_bool_10001_t));
    hg_slice_bool_t t1 = {.ptr = (*t0).elems+(0), .len = (((int64_t)10001))-(0), .cap = 10001-(0)};
    t4 = ((int64_t)2);
    goto blk3;
blk1:;
    hg_bounds_check(t4, t1.len, "/Users/apple/github/tamnd/hagane/testdata/primes/main.go:9", 0);
    bool* t2 = &t1.ptr[t4];
    *(t2) = true;
    int64_t t3 = hg_add_i64(t4, ((int64_t)1));
    t4 = t3;
    goto blk3;
blk2:;
    t8 = ((int64_t)2);
    goto blk6;
blk3:;
    bool t5 = t4 <= ((int64_t)10000);
    if (t5) goto blk1; else goto blk2;
blk4:;
    hg_bounds_check(t8, t1.len, "/Users/apple/github/tamnd/hagane/testdata/primes/main.go:12", 0);
    bool* t6 = &t1.ptr[t8];
    hg_nil_check(t6, "/Users/apple/github/tamnd/hagane/testdata/primes/main.go:12", 0);
    bool t7 = *((bool*)t6);
    if (t7) goto blk7; else goto blk8;
blk5:;
    t24 = ((int64_t)0);
    t25 = ((int64_t)2);
    goto blk13;
blk6:;
    int64_t t9 = hg_mul_i64(t8, t8);
    bool t10 = t9 <= ((int64_t)10000);
    if (t10) goto blk4; else goto blk5;
blk7:;
    int64_t t11 = hg_mul_i64(t8, t8);
    t15 = t11;
    goto blk10;
blk8:;
    int64_t t12 = hg_add_i64(t8, ((int64_t)1));
    t8 = t12;
    goto blk6;
blk9:;
    hg_bounds_check(t15, t1.len, "/Users/apple/github/tamnd/hagane/testdata/primes/main.go:14", 0);
    bool* t13 = &t1.ptr[t15];
    *(t13) = false;
    int64_t t14 = hg_add_i64(t15, t8);
    t15 = t14;
    goto blk10;
blk10:;
    bool t16 = t15 <= ((int64_t)10000);
    if (t16) goto blk9; else goto blk8;
blk11:;
    hg_bounds_check(t25, t1.len, "/Users/apple/github/tamnd/hagane/testdata/primes/main.go:20", 0);
    bool* t17 = &t1.ptr[t25];
    hg_nil_check(t17, "/Users/apple/github/tamnd/hagane/testdata/primes/main.go:20", 0);
    bool t18 = *((bool*)t17);
    t28 = t24;
    if (t18) goto blk14; else goto blk15;
blk12:;
    hg_array_hg_iface_t_1_t* t19 = (hg_array_hg_iface_t_1_t*)hg_alloc(sizeof(hg_array_hg_iface_t_1_t));
    hg_bounds_check(((int64_t)0), 1, "?", 0);
    hg_iface_t* t20 = &(*t19).elems[((int64_t)0)];
    hg_iface_t t21; { int64_t *_box = (int64_t*)hg_alloc(sizeof(int64_t)); *_box = t24; t21.data = _box; t21.itab = (const void*)&hg_itab_int64; }
    *(t20) = t21;
    hg_slice_hg_iface_t_t t22 = {.ptr = (*t19).elems+(0), .len = (1)-(0), .cap = 1-(0)};
    hg_fmt_println(t22);
    return;
blk13:;
    bool t26 = t25 <= ((int64_t)10000);
    if (t26) goto blk11; else goto blk12;
blk14:;
    int64_t t27 = hg_add_i64(t24, ((int64_t)1));
    t28 = t27;
    goto blk15;
blk15:;
    int64_t t29 = hg_add_i64(t25, ((int64_t)1));
    t24 = t28;
    t25 = t29;
    goto blk13;
}


int main(int argc, char **argv) {
    hg_runtime_init();
    hg_example_com_primes_main();
    return 0;
}
