/* generated by hagane — do not edit */
#include "hagane_rt.h"
#include "hagane_map.h"

bool hg_example_com_fib_init_guard;
int64_t hg_example_com_fib_fib(int64_t n);
void hg_example_com_fib_init(void);
void hg_example_com_fib_main(void);
typedef struct { hg_iface_t elems[1]; } hg_array_hg_iface_t_1_t;

int64_t hg_example_com_fib_fib(int64_t n) {
    goto blk0;
blk0:;
    bool t0 = n <= ((int64_t)1);
    if (t0) goto blk1; else goto blk2;
blk1:;
    return n;
blk2:;
    int64_t t1 = hg_sub_i64(n, ((int64_t)1));
    int64_t t2 = hg_example_com_fib_fib(t1);
    int64_t t3 = hg_sub_i64(n, ((int64_t)2));
    int64_t t4 = hg_example_com_fib_fib(t3);
    int64_t t5 = hg_add_i64(t2, t4);
    return t5;
}

void hg_example_com_fib_init(void) {
    goto blk0;
blk0:;
    hg_nil_check(&hg_example_com_fib_init_guard, "?", 0);
    bool t0 = *((bool*)&hg_example_com_fib_init_guard);
    if (t0) goto blk2; else goto blk1;
blk1:;
    hg_nil_check(&hg_example_com_fib_init_guard, "?", 0);
    *(&hg_example_com_fib_init_guard) = true;
    /* call to fmt.init skipped */
    goto blk2;
blk2:;
    return;
}

void hg_example_com_fib_main(void) {
    int64_t t0;
    memset(&t0, 0, sizeof(t0));
    goto blk0;
blk0:;
    t0 = ((int64_t)0);
    goto blk1;
blk1:;
    bool t1 = t0 < ((int64_t)10);
    if (t1) goto blk2; else goto blk3;
blk2:;
    bool t2 = t0 > ((int64_t)0);
    if (t2) goto blk4; else goto blk5;
blk3:;
    hg_fmt_println((hg_slice_hg_iface_t_t){0});
    return;
blk4:;
    hg_array_hg_iface_t_1_t* t4 = (hg_array_hg_iface_t_1_t*)hg_alloc(sizeof(hg_array_hg_iface_t_1_t));
    hg_bounds_check(((int64_t)0), 1, "?", 0);
    hg_iface_t* t5 = &(*t4).elems[((int64_t)0)];
    hg_iface_t t6; { hg_string_t *_box = (hg_string_t*)hg_alloc(sizeof(hg_string_t)); *_box = hg_string_lit(" "); t6.data = _box; t6.itab = (const void*)&hg_itab_string; }
    *(t5) = t6;
    hg_slice_hg_iface_t_t t7 = {.ptr = (*t4).elems+(0), .len = (1)-(0), .cap = 1-(0)};
    hg_fmt_print(t7);
    goto blk5;
blk5:;
    int64_t t9 = hg_example_com_fib_fib(t0);
    hg_array_hg_iface_t_1_t* t10 = (hg_array_hg_iface_t_1_t*)hg_alloc(sizeof(hg_array_hg_iface_t_1_t));
    hg_bounds_check(((int64_t)0), 1, "?", 0);
    hg_iface_t* t11 = &(*t10).elems[((int64_t)0)];
    hg_iface_t t12; { int64_t *_box = (int64_t*)hg_alloc(sizeof(int64_t)); *_box = t9; t12.data = _box; t12.itab = (const void*)&hg_itab_int64; }
    *(t11) = t12;
    hg_slice_hg_iface_t_t t13 = {.ptr = (*t10).elems+(0), .len = (1)-(0), .cap = 1-(0)};
    hg_fmt_print(t13);
    int64_t t15 = hg_add_i64(t0, ((int64_t)1));
    t0 = t15;
    goto blk1;
}


int main(int argc, char **argv) {
    hg_runtime_init();
    hg_example_com_fib_main();
    return 0;
}
