/* generated by hagane — do not edit */
#include "hagane_rt.h"
#include "hagane_map.h"

bool hg_example_com_multiret_init_guard;
typedef struct {
    int64_t r0;
    int64_t r1;
} hg_example_com_multiret_minmax_ret_t;

void hg_example_com_multiret_init(void);
void hg_example_com_multiret_main(void);
hg_example_com_multiret_minmax_ret_t hg_example_com_multiret_minmax(hg_slice_int64_t s);
typedef struct { int64_t elems[10]; } hg_array_int64_t_10_t;
typedef struct { hg_iface_t elems[2]; } hg_array_hg_iface_t_2_t;

void hg_example_com_multiret_init(void) {
    goto blk0;
blk0:;
    hg_nil_check(&hg_example_com_multiret_init_guard, "?", 0);
    bool t0 = *((bool*)&hg_example_com_multiret_init_guard);
    if (t0) goto blk2; else goto blk1;
blk1:;
    hg_nil_check(&hg_example_com_multiret_init_guard, "?", 0);
    *(&hg_example_com_multiret_init_guard) = true;
    /* call to fmt.init skipped */
    goto blk2;
blk2:;
    return;
}

void hg_example_com_multiret_main(void) {
    goto blk0;
blk0:;
    hg_array_int64_t_10_t* t0 = (hg_array_int64_t_10_t*)hg_alloc(sizeof(hg_array_int64_t_10_t));
    hg_bounds_check(((int64_t)0), 10, "?", 0);
    int64_t* t1 = &(*t0).elems[((int64_t)0)];
    *(t1) = ((int64_t)3);
    hg_bounds_check(((int64_t)1), 10, "?", 0);
    int64_t* t2 = &(*t0).elems[((int64_t)1)];
    *(t2) = ((int64_t)1);
    hg_bounds_check(((int64_t)2), 10, "?", 0);
    int64_t* t3 = &(*t0).elems[((int64_t)2)];
    *(t3) = ((int64_t)4);
    hg_bounds_check(((int64_t)3), 10, "?", 0);
    int64_t* t4 = &(*t0).elems[((int64_t)3)];
    *(t4) = ((int64_t)1);
    hg_bounds_check(((int64_t)4), 10, "?", 0);
    int64_t* t5 = &(*t0).elems[((int64_t)4)];
    *(t5) = ((int64_t)5);
    hg_bounds_check(((int64_t)5), 10, "?", 0);
    int64_t* t6 = &(*t0).elems[((int64_t)5)];
    *(t6) = ((int64_t)9);
    hg_bounds_check(((int64_t)6), 10, "?", 0);
    int64_t* t7 = &(*t0).elems[((int64_t)6)];
    *(t7) = ((int64_t)2);
    hg_bounds_check(((int64_t)7), 10, "?", 0);
    int64_t* t8 = &(*t0).elems[((int64_t)7)];
    *(t8) = ((int64_t)6);
    hg_bounds_check(((int64_t)8), 10, "?", 0);
    int64_t* t9 = &(*t0).elems[((int64_t)8)];
    *(t9) = ((int64_t)5);
    hg_bounds_check(((int64_t)9), 10, "?", 0);
    int64_t* t10 = &(*t0).elems[((int64_t)9)];
    *(t10) = ((int64_t)3);
    hg_slice_int64_t t11 = {.ptr = (*t0).elems+(0), .len = (10)-(0), .cap = 10-(0)};
    hg_example_com_multiret_minmax_ret_t t12 = hg_example_com_multiret_minmax(t11);
    int64_t t13 = t12.r0;
    int64_t t14 = t12.r1;
    hg_array_hg_iface_t_2_t* t15 = (hg_array_hg_iface_t_2_t*)hg_alloc(sizeof(hg_array_hg_iface_t_2_t));
    hg_bounds_check(((int64_t)0), 2, "?", 0);
    hg_iface_t* t16 = &(*t15).elems[((int64_t)0)];
    hg_iface_t t17; { int64_t *_box = (int64_t*)hg_alloc(sizeof(int64_t)); *_box = t13; t17.data = _box; t17.itab = (const void*)&hg_itab_int64; }
    *(t16) = t17;
    hg_bounds_check(((int64_t)1), 2, "?", 0);
    hg_iface_t* t18 = &(*t15).elems[((int64_t)1)];
    hg_iface_t t19; { int64_t *_box = (int64_t*)hg_alloc(sizeof(int64_t)); *_box = t14; t19.data = _box; t19.itab = (const void*)&hg_itab_int64; }
    *(t18) = t19;
    hg_slice_hg_iface_t_t t20 = {.ptr = (*t15).elems+(0), .len = (2)-(0), .cap = 2-(0)};
    hg_fmt_printf(hg_string_lit("min=%d max=%d\n"), t20);
    return;
}

hg_example_com_multiret_minmax_ret_t hg_example_com_multiret_minmax(hg_slice_int64_t s) {
    int64_t t6;
    memset(&t6, 0, sizeof(t6));
    int64_t t7;
    memset(&t7, 0, sizeof(t7));
    int64_t t8;
    memset(&t8, 0, sizeof(t8));
    int64_t t16;
    memset(&t16, 0, sizeof(t16));
    int64_t t22;
    memset(&t22, 0, sizeof(t22));
    goto blk0;
blk0:;
    int64_t t0 = s.len;
    bool t1 = t0 == ((int64_t)0);
    if (t1) goto blk1; else goto blk2;
blk1:;
    { hg_example_com_multiret_minmax_ret_t _ret; _ret.r0 = ((int64_t)0); _ret.r1 = ((int64_t)0); return _ret; }
blk2:;
    hg_bounds_check(((int64_t)0), s.len, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:9", 0);
    int64_t* t2 = &s.ptr[((int64_t)0)];
    hg_nil_check(t2, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:9", 0);
    int64_t t3 = *((int64_t*)t2);
    hg_bounds_check(((int64_t)0), s.len, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:9", 0);
    int64_t* t4 = &s.ptr[((int64_t)0)];
    hg_nil_check(t4, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:9", 0);
    int64_t t5 = *((int64_t*)t4);
    t6 = t3;
    t7 = t5;
    t8 = ((int64_t)1);
    goto blk3;
blk3:;
    int64_t t9 = s.len;
    bool t10 = t8 < t9;
    if (t10) goto blk4; else goto blk5;
blk4:;
    hg_bounds_check(t8, s.len, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:11", 0);
    int64_t* t11 = &s.ptr[t8];
    hg_nil_check(t11, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:11", 0);
    int64_t t12 = *((int64_t*)t11);
    bool t13 = t12 < t6;
    t16 = t6;
    if (t13) goto blk6; else goto blk7;
blk5:;
    { hg_example_com_multiret_minmax_ret_t _ret; _ret.r0 = t6; _ret.r1 = t7; return _ret; }
blk6:;
    hg_bounds_check(t8, s.len, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:12", 0);
    int64_t* t14 = &s.ptr[t8];
    hg_nil_check(t14, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:12", 0);
    int64_t t15 = *((int64_t*)t14);
    t16 = t15;
    goto blk7;
blk7:;
    hg_bounds_check(t8, s.len, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:14", 0);
    int64_t* t17 = &s.ptr[t8];
    hg_nil_check(t17, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:14", 0);
    int64_t t18 = *((int64_t*)t17);
    bool t19 = t18 > t7;
    t22 = t7;
    if (t19) goto blk8; else goto blk9;
blk8:;
    hg_bounds_check(t8, s.len, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:15", 0);
    int64_t* t20 = &s.ptr[t8];
    hg_nil_check(t20, "/Users/apple/github/tamnd/hagane/testdata/multiret/main.go:15", 0);
    int64_t t21 = *((int64_t*)t20);
    t22 = t21;
    goto blk9;
blk9:;
    int64_t t23 = hg_add_i64(t8, ((int64_t)1));
    t6 = t16;
    t7 = t22;
    t8 = t23;
    goto blk3;
}


int main(int argc, char **argv) {
    hg_runtime_init();
    hg_example_com_multiret_main();
    return 0;
}
